# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64d3002da944cd02f9f624804d7c09cdfb62d067121d5e427044e9aa14f51f7a63ec23674b1f7cac066de520eeb3c3857e6a01d8e9485665ff6655d1886c412c

test:
  secret_key_base: 405a1d547c470e8acfddd39283f0ef4c64933f9c5ad65fb444614b8801af848564694bb9cf2f0bf60a667fb7263ccb5d2e01600b3348a8bb8978d91759958848

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
